Repository somymat/django-app1, pull requests merged in 2019-08, with the labels that each got.

#1 add polls app
  basicApp/polls/__init__.py
  basicApp/polls/admin.py
  basicApp/polls/apps.py
  basicApp/polls/migrations/__init__.py
  basicApp/polls/models.py
  basicApp/polls/tests.py
  basicApp/polls/views.py
Labels: good first issue

#2 setting vscode
  .gitignore
Labels: documentation

#6 MongoDB Configuration
  basicApp/basicApp/settings.py
  basicApp/polls/admin.py
  basicApp/polls/migrations/0001_initial.py
  basicApp/polls/models.py
  requirements.txt
Labels: enhancement
